---
version: '3.3'

services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    #image: mcr.microsoft.com/mssql/server:2017-CU11-ubuntu
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "TestUAT123"
    ports:
      - 1433:1433
    volumes:
      - my-volume:/var/opt/mssql

  crawler:
    depends_on:
      - mssql
    container_name: crawler
    image: wb-parsing:latest
    # restart: always
    # environment:
    #   CONFIG_TYPE: yaml
    #   CONFIG_PATH: /usr/local/etc/crawler.yaml
    volumes:
      - ./secrets/uat_config.yaml:/opt/crawler/config.yaml:ro
      - ./logs:/opt/crawler/logs:rw

  # MS SQL Tools
  # docker run -it emergn/mssql-tools -S azuredatabase.database.windows.net -d azuresqldbname -U AADuser@example.com -P SecUrEpAsSwOrd -G

volumes:
  my-volume: